version: '3.7'
services:
    app:
        container_name: dockerized-react-app
        build:
            context: ./app
            dockerfile: Dockerfile
        volumes:
            - './app:/app'
            - '/app/node_modules'
        ports:
            - '3001:3000'
        environment:
            - NODE_ENV=development
    api:
        container_name: dockerized-nodets-api
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - './api:/app'
            - '/app/node_modules'
        ports:
            - '3002:3000'
        environment:
            - NODE_ENV=development